#  makefile.
#
#  g++ is the compiler.
#  -o sets the executable name
#
#  program     		-  Clueless
#  main.cpp   		-  main function


program: 
	g++ -o Clueless main.cpp Player.cpp Rooms.cpp

clean:
	\rm *.o *. Clueless